sudo: true
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && BUILD=Debug"

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && BUILD=Debug"

before_install:
- eval "${MATRIX_EVAL}"
- pip install --user cpp-coveralls
- git submodule update --init --recursive
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=$BUILD -DCOVERAGE=1 -DENABLE_GCOV=1 

script:
- make
- ./test/rapidstring_test
- cd test/CMakeFiles/rapidstring_test.dir/src
- ls
- if [[ $CC == gcc-7 ]]; then gcov *.gcno; fi

after_success:
- if [[ $CC == gcc-7 ]]; then
  cd ../../../../..;
  coveralls  -b build -r ./ -t tMUnrbng5NZDHK25YbasI8Wp7pmKZdmpS --exclude build --exclude benchmark  --exclude test/CMakeLists.txt --gcov-options "\-lp";
  fi

env:
  matrix:
    secure: "TMBsfujLAUYk2JXq4VJuTzbvnyi5yiIOoxTUblor9OK8IGQb+Ft2bxdTPtmvUHhPtYmHCDWflaAyIzBeB2wgwJaFFoK07dU+N8EtaPfmtiyrLAupf8bvA7MDsBFNZy26e7mbM8LzSkWkRAHDRgGYwlHcknhL201F1vzgb+uKyUHTEEWKVnuXBS7BeslVwvWCRL5Ph9CrQl/6NhauZSybvBDbI3suKcG4x1LeK3WshjrnIhBIt0H4dJaReNH05dc0Tq1tG/3kXh5hvBG7jKaVlMrqE+VMeE/PAJ1BUozddnbVhmyGd8iFQklKX1sEzrQ8JACg68sxkyTkum75cuRwthL01yqTVCSckGvr5HAVoMMqXaVDwvHddooMziWjpFMRO+wMDfrE1LpiTx4kqokIlehuGIO+ztrGL6ryZo+u8AcZN9QZwRDkXmuDbgiFoB1J69Rt26Kc3CwG5HmCAVFq/r4K8oJSqCnsHjkE1Bd8HHkBiXSyn6RqE++zw+QlzmqoixGTbHqF/CrWSedi/S+xNg5l6sHqNQPxTa0VI4oUsQ+t00b1LinScP6Wsi0UwPVCClgHdpsqkw5RpbJNyCKk3DVSGN6QaE48cDfNhlcCb1OZJ9O5zzg4XZx9V6p9gcpSWpx35oNiH69bfyiiPymGkm6HzSvkbC5J89UdzCUmMHI="	
